language: node_js
node_js:
  - 'lts/*'
cache:
  yarn: true
deploy:
  - provider: npm
    email: $email
    api_key: $api_key
    on:
      branch: master

  - provider: script
    github_token: $GITHUB_TOKEN
    script: bash docs.sh
    on:
      branch: master
script: yarn build
